<?php
namespace Modules\Admin\Http\Form;
use Library\Custom\Form;
use Library\Custom\Form\Element;

class TopGlobalNavigation extends Form {

    /** @var App\Repositories\OriginalSetting\OriginalSettingRepository */
    private $_originalSettings;

    public function setOriginalSettings($originalSettings){
        $this->_originalSettings = $originalSettings;
    }

    private function renderSelectNavigation(){
        $arr = [];
        for($i = 1; $i <= config('constants.original.MAX_GLOBAL_NAVIGATION'); $i++){
            $arr[(string)$i] =  $i;
        }
        return $arr;
    }

    public function init() {
        
        try{

            //company id
            $this->add(new Element\Hidden('company_id'));
            $this->add(new Element\Hidden('hd_id'));

            // global_navigation
            $select = new Element\Select('global_navigation');
            $select->setAttributes([
                'class'     => 'form-control ghostSelect',
                'onchange' => 'window.loadGlobalNavigation(this);',
                'id' => 'global_navigation_select'
            ]);
            $select->setRequired(true);
            $select->setValueOptions($this->renderSelectNavigation());
            $this->add($select);

        }
        catch(\Exception $e){
            return $e->getMessage();
        }
    }

    public function isValid($data, $checkError = true)
    {
        if($data['global_navigation'] <= 0 || $data['global_navigation'] > config('constants.original.MAX_GLOBAL_NAVIGATION'))
            return false;
        return parent::isValid($data, $checkError); // TODO: Change the autogenerated stub
    }


}