<?php
namespace Modules\Admin\Http\Form;
use Library\Custom\Model\Lists\Original;
use Library\Custom\Hp\Page\Parts\InfoList;

class TopNotificationSetting extends InfoList {

    protected $_fillField = array('page_size','cms_disable');

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        
        $this->_isTop = true;
        $this->_columnMap = array_merge($this->_columnMap,Original::$EXTEND_INFO_LIST);

        $disable = array(
            'parts_type_code',
            'sort',
            'column_sort',
            'display_flg',
            'heading_type'
        );

        $this->disableDefault($disable);
    }



    public function saveSetting(){
        $data = array();
        foreach ($this->getElements() as $name => $element) {
            $value = $element->getValue();
            if (isEmpty($value)) {
                continue;
            }

            if(!in_array($name, $this->_fillField)) continue;

            if (isset($this->_columnMap[$name])) {
                $name = $this->_columnMap[$name];
            }

            $data[$name] = $value;
        }
        $table = $this->getSaveTable();
        $id = $this->getElement('id')->getValue();
        $table->update(array(['id', $id]), $data);
    }
}