<?php $this->headStyle()->captureStart() ?>
.hide {
	display: none;
}
#modal {
	background-color: rgba(0,0,0,0.7);
	position:fixed;
	height: 100%;
	width: 100%;
	top: 0;
	left: 0;
}

.modal-body {
	position: absolute;
	top:0;
	left: 0;
	right: 0;
	bottom: 0;
	margin: auto;
	background-color: #fff;
	border-radius: 3px;
}
.modal-body h3 {
	padding: 10px;
	border-bottom: 1px solid #ec9;
	font-size: 14px;
	font-weight: bold;
	color: #333;
}
.modal-body p {
	padding: 20px 50px;
}
.modal-body .btns {
	text-align:center;
}
.modal-body .btns .btn {
	display: inline-block;
	width: 100px;
	border: 1px solid #ec9;
	padding: 5px;
	font-size: 12px;
	font-weight: bold;
	color: #333;
	cursor: pointer;
}
.modal-body .btns .btn:hover {
	background-color: #ec9;
	color: #fff;
}
.modal-body-progress {
	width: 500px;
	height: 250px;
}
.progress-bar {
	margin: auto;
	height: 30px;
	width: 80%;
	border: 1px solid #ec9;
}
.progress-bar div {
	width: 0;
	height: 100%;
	background-color: #ec9;
	transition: all 300ms ease-out 0s;
}
.progress-iframe {
	width: 0;
	height: 0;
	position: absolute;
	left: -100;
	top: -100;
}
<?php $this->headStyle()->captureEnd() ?>
<?php $this->headScript()->captureStart() ?>
function testUpdate(res) {
}
function testFinish() {
}
$(function () {
	var $modal = $('#modal').addClass('hide');
	var $confirm = $modal.find('.confirm');
	var $complete = $modal.find('.complete');
	var $progress = $modal.find('.progress');
	var $progressBar = $progress.find('.progress-bar');
	var $progressCurrent = $progress.find('.progress-current');
	var $progressMax = $progress.find('.progress-max');
	
	$('#show-confirm').on('click', function() {
		$confirm.removeClass('hide');
		$progress.addClass('hide');
		$complete.addClass('hide');
		$modal.removeClass('hide');
	});
	
	$('.close').on('click', function () {
		$modal.addClass('hide');
	});
	$('#ok').on('click', function () {
		$confirm.addClass('hide');
		$complete.addClass('hide');
		$progress.removeClass('hide');
		
		$progressMax.text('-');
		$progressMax.text('-');
		
		$progressBar.empty();
		var $progressBarPer = $('<div/>').appendTo($progressBar);
		
		$iframe = $('<iframe/>');
		
		window.testUpdate = function (res) {
			$progressCurrent.text(res.current);
			$progressMax.text(res.max);
			$progressBarPer.css('width', res.percent + '%');
		};
		window.testFinish = function () {
			$confirm.addClass('hide');
			$progress.addClass('hide');
			$complete.removeClass('hide');
			
			$iframe.remove();
			
			window.testUpdate = $.noop;
			window.testFinish = $.noop;
		};
		
		$iframe
			.addClass('progress-iframe')
			.attr('src', '/sample/progress-bar')
			.appendTo('body');
	});
});
<?php $this->headScript()->captureEnd() ?>
<input id="show-confirm" type="button" value="公開"/>
<div id="modal" class="hide">
	<div class="modal-body modal-body-progress">
		<div class="confirm">
			<h3>公開確認</h3>
			<p>設定した内容でサイトを公開します。<br>よろしいですか？</p>
			<div class="btns">
				<a class="btn close">キャンセル</a>
				<a class="btn" id="ok">OK</a>
			</div>
		</div>
		
		<div class="progress hide">
			<h3>公開処理中…</h3>
			<p>公開処理中です。しばらくお待ち下さい。<br>（<span class="progress-current"></span>/<span class="progress-max"></span>件）</p>
			<div class="progress-bar"><div></div></div>
		</div>
		
		<div class="complete hide">
			<h3>公開完了</h3>
			<p>公開処理が完了しました。</p>
			<div class="btns">
				<a class="btn close">OK</a>
			</div>
		</div>
	</div>
</div>
